server.port=${PORT:8080}

spring.messages.basename=messages
spring.messages.fallback-to-system-locale=false
spring.messages.encoding=UTF-8

# TiDB (MySQL) Configuration
spring.profiles.active=local

# SQL Server
# spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=QL_ChungCu;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true;
# spring.datasource.username=sa
# spring.datasource.password=12345678

# MySQL 8 Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true